In [15]:
from ALLCools.mcds import RegionDS
from ALLCools.dmr import call_dms, call_dmr
import glob as glob
import pandas as pd
import numpy as np
import os

In [16]:
brain_regions = ['PFC','AMY','HIP']

In [17]:
cell_types = ['Neuron','Astro-Epen','Vascular','Immune','OPC-Oligo']

In [18]:
celltype = cell_types[0]
brain_region = brain_regions[0]

In [19]:
mc_bulk_dir = f'/data2st1/junyi/merged_allcs/{brain_region}/'
allc_paths = glob.glob(f'{mc_bulk_dir}/*.tsv.gz')

In [ ]:
# 3rd column is the orginal id in the wilcox table
# df_dar = pd.read_csv(f'/data2st1/junyi/output/motif/ALL_{celltype}_wilcoxon_DAR_lifted_sorted_gene.bed',sep='\t',header=None,index_col=3)
# df_dar.columns = ['chr','start','end','chrmm10','startmm10','endmm10','score','strand','gene_name','gene_id','region','distance']
# df_pval = pd.read_csv(f'/data2st1/junyi/output/motif/ALL_{celltype}_wilcoxon.csv',index_col=0)
# df_concatted= pd.concat([df_pval.loc[df_dar.index],df_dar],axis=1)
# df_dar_selected = df_concatted[(df_concatted.pvals<0.05) & (df_concatted.logfoldchanges>0.1)& (df_concatted.pct_nz_group>0.1)]
# df_dar_selected['regionmm10'] = df_dar_selected['chr'] + ':' + df_dar_selected['start'].astype(str) + '-' + df_dar_selected['end'].astype(str)
# df_dar_selected['region_extended'] = df_dar_selected['chr'] + ':' + (df_dar_selected['start']-5000).astype(str) + '-' + (df_dar_selected['end']+5000).astype(str)

/tmp/ipykernel_2508315/679740978.py:7: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_dar_selected['regionmm10'] = df_dar_selected['chr'] + ':' + df_dar_selected['start'].astype(str) + '-' + df_dar_selected['end'].astype(str)
/tmp/ipykernel_2508315/679740978.py:8: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_dar_selected['region_extended'] = df_dar_selected['chr'] + ':' + (df_dar_selected['start']-5000).astype(str) + '-' + (df_dar_selected['end']+5000).astype(str)


In [57]:
df_dar = pd.read_csv('/data1st2/hannan_25/data/Nanopore_process/nanopore_08_differential/pair_base/C_dmrpair_F_HIP_vs_PFC.segment',sep='\t',header=None,index_col=None)
df_dar.columns = ['chr','start','end','state','scores','nsties','counta','couontb','pcta','pctb','fraca','fracb','effectsize']
df_dar_selected = df_dar[(df_dar['state'].isin(['different'])) & (df_dar['chr'].str.len()<=2) & (df_dar['fracb']>0.1) & (df_dar['effectsize']<0)]
df_dar_selected['regionmm10'] = 'chr'+df_dar_selected['chr'] + ':' + df_dar_selected['start'].astype(str) + '-' + df_dar_selected['end'].astype(str)
df_dar_selected['region_extended'] = 'chr'+df_dar_selected['chr'] + ':' + (df_dar_selected['start']-5000).astype(str) + '-' + (df_dar_selected['end']+5000).astype(str)

/tmp/ipykernel_2508315/1512998197.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_dar_selected['regionmm10'] = 'chr'+df_dar_selected['chr'] + ':' + df_dar_selected['start'].astype(str) + '-' + df_dar_selected['end'].astype(str)
/tmp/ipykernel_2508315/1512998197.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_dar_selected['region_extended'] = 'chr'+df_dar_selected['chr'] + ':' + (df_dar_selected['start']-5000).astype(str) + '-' + (df_dar_selected['end']+5000).astype(str)


In [60]:
df_dar_selected.sort_values(by='scores',ascending=False)

chr      start        end      state      scores  nsties         counta  \
19103   5  116478887  116478906  different  168.399065      19     h:69,m:220   
6285   13   78184643   78184841  different  159.601391      93     h:42,m:141   
39052   Y   90794037   90794067  different  153.709346      27   h:121,m:8331   
13512   2   98666709   98666771  different  151.803719      25  h:521,m:33229   
16988   4   87432291   87432329  different  151.436004      38      h:6,m:534   
...    ..        ...        ...        ...         ...     ...            ...   
29740   9   49151886   49151925  different   -0.427192      23      h:6,m:591   
34306   X   38315856   38315858  different   -0.457143       2       h:0,m:23   
35469   X   77414722   77414751  different   -0.572276      17     h:14,m:228   
38806   Y   90740368   90740376  different   -0.618455       5     h:13,m:475   
24670   8   20150139   20150145  different   -0.655382       5     h:12,m:264   

             couontb             pcta             pctb     fraca     fracb  \
19103    h:229,m:160  h:12.15,m:38.73  h:55.85,m:39.02  0.508803  0.948781   
6285     h:168,m:298    h:0.96,m:3.22   h:5.92,m:10.51  0.041771  0.164316   
39052   h:133,m:3894   h:1.17,m:80.77   h:3.04,m:88.88  0.819389  0.919197   
13512  h:712,m:21851   h:0.42,m:26.49   h:0.93,m:28.45  0.269016  0.293808   
16988      h:6,m:580   h:0.54,m:48.50   h:0.90,m:87.35  0.490463  0.882530   
...              ...              ...              ...       ...       ...   
29740      h:2,m:199   h:0.70,m:69.37   h:0.72,m:71.58  0.700704  0.723022   
34306        h:0,m:7   h:0.00,m:47.92   h:0.00,m:58.33  0.479167  0.583333   
35469       h:7,m:91   h:2.41,m:39.18   h:3.00,m:39.06  0.415808  0.420601   
38806      h:6,m:236   h:0.87,m:31.65   h:0.82,m:32.42  0.325117  0.332418   
24670       h:4,m:76   h:1.98,m:43.64   h:2.29,m:43.43  0.456198  0.457143   

       effectsize                regionmm10           region_extended  
19103   -0.439978  chr5:116478887-116478906  chr5:116473887-116483906  
6285    -0.122545   chr13:78184643-78184841   chr13:78179643-78189841  
39052   -0.099807    chrY:90794037-90794067    chrY:90789037-90799067  
13512   -0.024792    chr2:98666709-98666771    chr2:98661709-98671771  
16988   -0.392067    chr4:87432291-87432329    chr4:87427291-87437329  
...           ...                       ...                       ...  
29740   -0.022317    chr9:49151886-49151925    chr9:49146886-49156925  
34306   -0.104167    chrX:38315856-38315858    chrX:38310856-38320858  
35469   -0.004793    chrX:77414722-77414751    chrX:77409722-77419751  
38806   -0.007301    chrY:90740368-90740376    chrY:90735368-90745376  
24670   -0.000945    chr8:20150139-20150145    chr8:20145139-20155145  

[6387 rows x 15 columns]

In [136]:
df_dar_selected

chr     start       end      state     scores  nsties      counta  \
1       1   3064927   3064929  different  26.685243       2     h:0,m:0   
3       1   3734993   3734995  different  37.454968       2     h:0,m:1   
19      1   6526617   6526633  different  28.960890       6     h:4,m:3   
21      1   6527054   6527089  different  13.846013      14    h:7,m:11   
27      1   7026106   7026107  different  18.837102       1     h:0,m:0   
...    ..       ...       ...        ...        ...     ...         ...   
39126   Y  90807380  90807382  different  30.930988       2    h:0,m:18   
39128   Y  90807414  90807415  different  35.765283       1     h:0,m:2   
39132   Y  90807806  90807826  different  14.077198      10  h:67,m:769   
39134   Y  90808876  90808878  different   9.732585       2  h:38,m:446   
39142   Y  90811072  90811087  different  24.311481       8  h:49,m:248   

          couontb            pcta             pctb     fraca     fracb  \
1        h:0,m:19   h:0.00,m:0.00   h:0.00,m:48.72  0.000000  0.487179   
3        h:0,m:37   h:0.00,m:2.70   h:0.00,m:92.50  0.027027  0.925000   
19       h:5,m:34   h:1.77,m:1.33   h:3.88,m:26.36  0.030973  0.302326   
21      h:12,m:29   h:1.36,m:2.13    h:4.04,m:9.76  0.034884  0.138047   
27        h:0,m:9   h:0.00,m:0.00   h:0.00,m:90.00  0.000000  0.900000   
...           ...             ...              ...       ...       ...   
39126    h:0,m:36   h:0.00,m:3.05   h:0.00,m:25.17  0.030457  0.251748   
39128    h:2,m:19   h:0.00,m:0.47   h:2.70,m:25.68  0.004739  0.283784   
39132  h:78,m:342  h:1.63,m:18.73   h:3.96,m:17.34  0.203604  0.212982   
39134  h:40,m:185  h:4.71,m:55.33  h:12.08,m:55.89  0.600496  0.679758   
39142   h:69,m:84   h:1.39,m:7.04    h:5.06,m:6.16  0.084351  0.112252   

       effectsize              regionmm10         region_extended  
1       -0.487179    chr1:3064927-3064929    chr1:3059927-3069929  
3       -0.897973    chr1:3734993-3734995    chr1:3729993-3739995  
19      -0.271352    chr1:6526617-6526633    chr1:6521617-6531633  
21      -0.103163    chr1:6527054-6527089    chr1:6522054-6532089  
27      -0.900000    chr1:7026106-7026107    chr1:7021106-7031107  
...           ...                     ...                     ...  
39126   -0.221291  chrY:90807380-90807382  chrY:90802380-90812382  
39128   -0.279044  chrY:90807414-90807415  chrY:90802414-90812415  
39132   -0.009377  chrY:90807806-90807826  chrY:90802806-90812826  
39134   -0.079262  chrY:90808876-90808878  chrY:90803876-90813878  
39142   -0.027901  chrY:90811072-90811087  chrY:90806072-90816087  

[6387 rows x 15 columns]

In [61]:
allc_table= {}

for allc_path in cell_types:
    #allc_table["/data2st1/junyi/merged_allcs/PFC/"+allc_path] = mc_bulk_dir+allc_path+'.tsv.gz'
    allc_table[allc_path] = mc_bulk_dir+allc_path+'.tsv.gz'


In [62]:
allc_table

{'Neuron': '/data2st1/junyi/merged_allcs/PFC/Neuron.tsv.gz',
 'Astro-Epen': '/data2st1/junyi/merged_allcs/PFC/Astro-Epen.tsv.gz',
 'Vascular': '/data2st1/junyi/merged_allcs/PFC/Vascular.tsv.gz',
 'Immune': '/data2st1/junyi/merged_allcs/PFC/Immune.tsv.gz',
 'OPC-Oligo': '/data2st1/junyi/merged_allcs/PFC/OPC-Oligo.tsv.gz'}

In [65]:
# make a dict, key is sample name, value is allc path
# import pathlib
# allc_table = {
#     allc_path.name.split('.')[0]: str(allc_path)
#     for allc_path in pathlib.Path(mc_bulk_dir).glob(
#         f'{mc_bulk_dir}/*.tsv.gz')
# }
celltype = 'Nano_PFC_HIP'
samples = list(allc_table.keys())
allc_paths = list(allc_table.values())
chrom_size_path = '/home/junyichen/code/whole_mouse_brain/wmb/files/mm10.main.chrom.sizes'
output_dir = f'/data2st1/junyi/output/dmr/{brain_region}/{celltype}/'


In [66]:
if os.path.exists(output_dir) == False:
    os.makedirs(output_dir)

In [84]:
input_region = df_dar_selected.sort_values(by='scores',ascending=False).head(500)
input_region.sort_values(['chr','start','end'],inplace=True)
input_region.drop_duplicates(subset=['chr','start','end'],keep='first',inplace=True)
df_top = input_region
input_region = input_region.regionmm10.values.tolist()  

In [86]:
call_dms(
    output_dir=output_dir,
    allc_paths=allc_paths,
    samples=samples,
    chrom_size_path=chrom_size_path,
    cpu=16,
    max_row_count=50,
    n_permute=3000,
    min_pvalue=0.01,
    # here we just calculate some small regions for demo
    # do not provide region parameter if you want to run DMR calling for the whole genome
    # This parameter can also be used for call DMR/DMS in specific region of interest
    region=input_region)


RMS tests for 6 sites.
RMS tests for 5 sites.RMS tests for 22 sites.RMS tests for 44 sites.

RMS tests for 11 sites.
RMS tests for 6 sites.

RMS tests for 10 sites.
RMS tests for 35 sites.
RMS tests for 13 sites.
RMS tests for 6 sites.
RMS tests for 10 sites.
RMS tests for 29 sites.
RMS tests for 12 sites.RMS tests for 11 sites.

RMS tests for 18 sites.RMS tests for 31 sites.

RMS tests for 6 sites.
RMS tests for 39 sites.
RMS tests for 11 sites.
RMS tests for 13 sites.
RMS tests for 4 sites.
RMS tests for 61 sites.
RMS tests for 8 sites.
RMS tests for 30 sites.
RMS tests for 8 sites.
RMS tests for 1 sites.
RMS tests for 1 sites.
RMS tests for 1 sites.
RMS tests for 63 sites.
RMS tests for 15 sites.
RMS tests for 4 sites.
RMS tests for 11 sites.
RMS tests for 10 sites.
RMS tests for 5 sites.
RMS tests for 6 sites.
RMS tests for 7 sites.
RMS tests for 40 sites.
RMS tests for 12 sites.
RMS tests for 9 sites.
RMS tests for 12 sites.
RMS tests for 13 sites.
RMS tests for 4 sites.
RMS tests

In [89]:
call_dmr(output_dir=output_dir,
         p_value_cutoff=0.001,
         frac_delta_cutoff=0.3,
         max_dist=250,
         residual_quantile=0.7,
         corr_cutoff=0.3,
         cpu=16)

In [88]:
dmr_ds = RegionDS.open(output_dir)
dmr_ds


Using dmr as region_dim


<xarray.RegionDS>
Dimensions:      (count_type: 2, dmr: 164, sample: 5)
Coordinates:
  * count_type   (count_type) <U3 'mc' 'cov'
  * dmr          (dmr) <U8 'chr1-0' 'chr1-1' 'chr1-2' ... 'chr19-6' 'chrX-0'
    dmr_chrom    (dmr) <U5 dask.array<chunksize=(32,), meta=np.ndarray>
    dmr_end      (dmr) int64 dask.array<chunksize=(32,), meta=np.ndarray>
    dmr_length   (dmr) int64 dask.array<chunksize=(32,), meta=np.ndarray>
    dmr_ndms     (dmr) int64 dask.array<chunksize=(32,), meta=np.ndarray>
    dmr_start    (dmr) int64 dask.array<chunksize=(32,), meta=np.ndarray>
  * sample       (sample) <U10 'Neuron' 'Astro-Epen' ... 'Immune' 'OPC-Oligo'
Data variables:
    dmr_da       (sample, dmr, count_type) uint32 dask.array<chunksize=(1, 32, 1), meta=np.ndarray>
    dmr_da_frac  (sample, dmr) float32 dask.array<chunksize=(1, 32), meta=np.ndarray>
    dmr_state    (sample, dmr) int8 dask.array<chunksize=(1, 32), meta=np.ndarray>
Attributes:
    region_dim:          dmr
    region_ds_location:  /data2st1/junyi/output/dmr/PFC/Nano_PFC_HIP
    chrom_size_path:     /data2st1/junyi/output/dmr/PFC/Nano_PFC_HIP/chrom_si...

In [90]:
df_dmr = pd.DataFrame(
    {
        'chr': dmr_ds['dmr_chrom'].to_numpy(),
        'start': dmr_ds['dmr_start'].to_numpy(),
        'end': dmr_ds['dmr_end'].to_numpy(),
    }
)

In [91]:
sample_mapping = {}
for i in range(len(dmr_ds['sample'].to_numpy())):
    sample_mapping[i] = dmr_ds['sample'].to_numpy()[i]
sample_mapping

{0: 'Neuron', 1: 'Astro-Epen', 2: 'Vascular', 3: 'Immune', 4: 'OPC-Oligo'}

In [92]:
drm_state = dmr_ds['dmr_state'].to_numpy()
for i in range(len(drm_state)):
    df_dmr[sample_mapping[i]] = drm_state[i]

In [93]:
df_dmr.to_csv(f'{output_dir}/dmr_stat.csv',index=False)

In [94]:
dmr_ds['dmr_da_frac'].to_numpy()

array([[0.6956522 , 0.9358974 , 0.7394366 , 0.8586956 , 0.84444445,
        0.7181572 , 0.7368421 , 0.7184466 , 0.22429906, 0.8626506 ,
        0.5613383 , 0.36842105, 0.7924528 , 0.7702703 , 0.7121212 ,
        0.84615386, 0.877712  , 0.8844221 , 0.8119266 , 0.6151419 ,
        0.93037975, 0.78571427, 0.776     , 0.5952381 , 0.62068963,
        0.92896175, 0.67156863, 0.77205884, 0.7789855 , 0.91167194,
        0.8089172 , 0.5945946 , 0.88110405, 0.89074355, 0.93037975,
        0.93333334, 0.87677723, 0.78640777, 0.8310811 , 0.5770393 ,
        0.87763715, 0.5959596 , 0.89365673, 0.6712329 , 0.7169811 ,
        0.65591395, 0.84187084, 0.67826086, 0.80851066, 0.60096157,
        0.60805863, 0.6302083 , 0.5416667 , 0.84375   , 0.9259259 ,
        0.50980395, 0.90654206, 0.8863636 , 0.8465753 , 0.875     ,
        0.5614035 , 0.82033896, 0.6944444 , 0.7647059 , 0.77312773,
        0.8465753 , 0.94418603, 0.46031746, 0.81193256, 0.9794521 ,
        0.8484849 , 0.8122271 , 0.82222223, 0.94

In [95]:
np.save(f'{output_dir}/dmr_frac.npy', dmr_ds['dmr_da_frac'].to_numpy())


In [160]:
NN_marker = dmr_ds['dmr_state'][0]==-1

In [181]:
dmr_nn = dmr_ds.sel(dmr=NN_marker.to_numpy())

In [185]:
dmr_nn['dmr_da_frac'].to_numpy()[:,0]

array([0.22429906, 0.68      , 0.7       , 1.        , 0.37037036],
      dtype=float32)

In [186]:
dmr_nn['dmr_da_frac'].to_numpy()[:,1]

array([0.36842105, 1.        , 1.        , 1.        , 0.6363636 ],
      dtype=float32)

In [211]:
dmr_nn['dmr_start'].to_numpy()

array([ 90486466, 132730271,  59350487,  82964798,  69564613,  69572318,
        46822596])

In [212]:
dmr_nn['sample']

<xarray.DataArray 'sample' (sample: 5)>
array(['Neuron', 'Astro-Epen', 'Vascular', 'Immune', 'OPC-Oligo'], dtype='<U10')
Coordinates:
  * sample   (sample) <U10 'Neuron' 'Astro-Epen' 'Vascular' 'Immune' 'OPC-Oligo'

In [207]:
dmr_nn['dmr_da_frac'].to_numpy()[:,:].round(3)

array([[0.224, 0.368, 0.544, 0.125, 0.4  , 0.557, 0.533],
       [0.68 , 1.   , 0.933, 0.   , 0.5  , 0.96 , 1.   ],
       [0.7  , 1.   , 0.833, 1.   , 1.   , 1.   , 1.   ],
       [1.   , 1.   , 1.   , 1.   , 1.   , 1.   , 1.   ],
       [0.37 , 0.636, 1.   , 0.714, 1.   , 0.99 , 1.   ]], dtype=float32)

In [197]:
dmr_nn['dmr_da'].to_numpy()[:,:,0]

array([[ 24,  21,  31,   3,  14, 172,  24],
       [ 17,  11,  14,   0,   5,  48,  10],
       [  7,   4,   5,   3,   5,  16,   4],
       [ 10,   5,   3,   7,   2,  18,   4],
       [ 10,   7,  12,   5,  11,  96,   5]], dtype=uint32)

In [198]:
dmr_nn['dmr_da'].to_numpy()[:,:,1]

array([[107,  57,  57,  24,  35, 309,  45],
       [ 25,  11,  15,  10,  10,  50,  10],
       [ 10,   4,   6,   3,   5,  16,   4],
       [ 10,   5,   3,   7,   2,  18,   4],
       [ 27,  11,  12,   7,  11,  97,   5]], dtype=uint32)

In [101]:
dms_ds = RegionDS.open(output_dir, region_dim='dms')
dms_ds


<xarray.RegionDS>
Dimensions:       (count_type: 2, dms: 943, sample: 5)
Coordinates:
  * count_type    (count_type) <U3 'mc' 'cov'
  * dms           (dms) <U15 'chr1-37820074' ... 'chrX-162898192'
    dms_chrom     (dms) <U5 dask.array<chunksize=(188,), meta=np.ndarray>
    dms_contexts  (dms) <U3 dask.array<chunksize=(188,), meta=np.ndarray>
    dms_p-values  (dms) float64 dask.array<chunksize=(188,), meta=np.ndarray>
    dms_pos       (dms) int64 dask.array<chunksize=(188,), meta=np.ndarray>
  * sample        (sample) <U10 'Neuron' 'Astro-Epen' ... 'Immune' 'OPC-Oligo'
Data variables:
    dms_da        (sample, dms, count_type) float64 dask.array<chunksize=(1, 188, 1), meta=np.ndarray>
    dms_da_frac   (sample, dms) float64 dask.array<chunksize=(1, 188), meta=np.ndarray>
    dms_residual  (sample, dms) float64 dask.array<chunksize=(1, 188), meta=np.ndarray>
Attributes:
    region_dim:          dms
    region_ds_location:  /data2st1/junyi/output/dmr/PFC/Nano_PFC_HIP
    chrom_size_path:     /data2st1/junyi/output/dmr/PFC/Nano_PFC_HIP/chrom_si...

In [205]:
dms_ds['dms_residual'].to_numpy().shape

(5, 943)

In [133]:
chrom_filter = dms_ds['dms_p-values'] <0.05 # 创建布尔掩码


In [134]:
filtered_ds = dms_ds.where(chrom_filter, drop=True)

In [137]:
filtered_ds

<xarray.Dataset>
Dimensions:       (sample: 5, dms: 943, count_type: 2)
Coordinates:
  * count_type    (count_type) <U3 'mc' 'cov'
  * dms           (dms) <U15 'chr1-37820074' ... 'chrX-162898192'
    dms_chrom     (dms) <U5 dask.array<chunksize=(188,), meta=np.ndarray>
    dms_contexts  (dms) <U3 dask.array<chunksize=(188,), meta=np.ndarray>
    dms_p-values  (dms) float64 dask.array<chunksize=(188,), meta=np.ndarray>
    dms_pos       (dms) int64 dask.array<chunksize=(188,), meta=np.ndarray>
  * sample        (sample) <U10 'Neuron' 'Astro-Epen' ... 'Immune' 'OPC-Oligo'
Data variables:
    dms_da        (sample, dms, count_type) float64 dask.array<chunksize=(1, 188, 1), meta=np.ndarray>
    dms_da_frac   (sample, dms) float64 dask.array<chunksize=(1, 188), meta=np.ndarray>
    dms_residual  (sample, dms) float64 dask.array<chunksize=(1, 188), meta=np.ndarray>
Attributes:
    region_dim:          dms
    region_ds_location:  /data2st1/junyi/output/dmr/PFC/Nano_PFC_HIP
    chrom_size_path:     /data2st1/junyi/output/dmr/PFC/Nano_PFC_HIP/chrom_si...